#!/usr/bin/env bash
# Build the Python type module for the Fast DDS demo participant (Linux).
#
# This script does NOT build Fast DDS or its Python binding: `fastdds` is not
# a PyPI package. Install them first (see README.md), then point FASTDDS_HOME
# at the install prefix that holds Fast DDS 3.x, Fast-CDR and fastdds_python
# (for a colcon workspace: <ws>/install after `colcon build --merge-install`).
#
# Needs: fastddsgen on PATH (Fast-DDS-Gen, Java >= 17), SWIG < 4.2, cmake,
# a C++ compiler, python3 development headers.
# Output: ./build/env.sh, sourced by run.sh.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD="$HERE/build"
GEN="$BUILD/gen"
INSTALL="$BUILD/install"
PYTHON="${PYTHON:-python3}"

: "${FASTDDS_HOME:?set FASTDDS_HOME to the install prefix of Fast DDS 3.x + fastdds_python}"
command -v fastddsgen >/dev/null || { echo "error: fastddsgen not on PATH" >&2; exit 1; }
command -v swig >/dev/null || { echo "error: swig not on PATH (need < 4.2)" >&2; exit 1; }
command -v cmake >/dev/null || { echo "error: cmake not on PATH" >&2; exit 1; }

mkdir -p "$BUILD"
rm -rf "$GEN" "$INSTALL"
mkdir -p "$GEN"

# 1. IDL -> C++ type support + SWIG interface + CMakeLists.txt (Heartbeat module).
fastddsgen -python -replace -d "$GEN" "$HERE/Heartbeat.idl"

# 2. Build and install libHeartbeat + the SWIG wrapper into build/install.
cmake -S "$GEN" -B "$BUILD/cmake" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_PREFIX_PATH="${FASTDDS_HOME}${CMAKE_PREFIX_PATH:+;$CMAKE_PREFIX_PATH}" \
    -DPython3_EXECUTABLE="$(command -v "$PYTHON")" \
    -DCMAKE_INSTALL_PREFIX="$INSTALL"
cmake --build "$BUILD/cmake" -j
cmake --install "$BUILD/cmake"

# 3. Record where the modules landed so run.sh can set the environment.
HB_PKG="$(find "$INSTALL" -type f -path '*/Heartbeat/__init__.py' | head -n 1)"
[ -n "$HB_PKG" ] || { echo "error: Heartbeat python package not installed" >&2; exit 1; }
HB_PYDIR="$(dirname "$(dirname "$HB_PKG")")"
FD_PKG="$(find "$FASTDDS_HOME" -type f -path '*/fastdds/__init__.py' | head -n 1)"
[ -n "$FD_PKG" ] || { echo "error: no fastdds python package under $FASTDDS_HOME" >&2; exit 1; }
FD_PYDIR="$(dirname "$(dirname "$FD_PKG")")"

cat > "$BUILD/env.sh" <<ENV
# Generated by build.sh. Sourced by run.sh.
export PYTHON="$PYTHON"
export PYTHONPATH="$HB_PYDIR:$FD_PYDIR\${PYTHONPATH:+:\$PYTHONPATH}"
export LD_LIBRARY_PATH="$INSTALL/lib:$FASTDDS_HOME/lib\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
ENV

echo "built the Heartbeat type module; start the participant with $HERE/run.sh --domain N"
