"""Cross-backend helpers: pure logic shared between adapters."""

from topicforge.adapters.common.cdr_decoder import (
    decode_dynamic_sample,
    decode_field_value,
    dynamic_type_name,
    extract_publish_ns_from_payload,
    extract_seq_from_payload,
    iter_field_names,
)
from topicforge.adapters.common.dds_helpers import (
    DDS_ONLY_ERROR_MSG,
    DYNAMIC_DECODE_DISABLED_NOTE,
    VendorTag,
    canonicalize_vendor_id,
    format_guid,
    take_bounded,
    user_topic_placeholder,
    validate_domain_id,
)
from topicforge.adapters.common.dds_introspection import (
    cyclone_extract_guid,
    cyclone_extract_hostname,
    cyclone_extract_participant_name,
    cyclone_extract_topic_name,
    cyclone_extract_type_name,
    cyclone_extract_vendor_id,
    fast_extract_guid,
    fast_extract_hostname,
    fast_extract_topic_name,
    fast_extract_vendor_id,
    is_alive_sample,
    is_removal,
    vendor_id_from_guid,
)
from topicforge.adapters.common.discovery_tracker import (
    DEFAULT_PERIOD_S,
    DiscoveryCaches,
    DiscoveryTracker,
    SampleCache,
    apply_builtin_samples,
)
from topicforge.adapters.common.endpoints import (
    MAX_LISTED_ENDPOINTS,
    announced_ns_of,
    build_endpoint_listing,
    builtin_payload,
    endpoint_record,
    format_participant_key,
    listing_from_samples,
    participant_names,
    summarize_by_topic,
    type_id_text,
)
from topicforge.adapters.common.lifecycle import MAX_EVENTS, LifecycleBuffer
from topicforge.adapters.common.metrics_buffer import (
    MAX_SAMPLES_PER_TOPIC,
    MetricsBuffer,
    MetricsSample,
)
from topicforge.adapters.common.qos_analyzer import detect_mismatches
from topicforge.adapters.common.qos_endpoints import detect_mismatches_across_endpoints
from topicforge.adapters.common.qos_normalize import (
    cyclone_qos_to_profile,
    duration_to_ns,
    fast_qos_to_profile,
)
from topicforge.adapters.common.xtypes import (
    DecodeStatus,
    annotate_full,
    annotate_partial,
    annotate_raw,
)

__all__ = [
    "DDS_ONLY_ERROR_MSG",
    "DEFAULT_PERIOD_S",
    "DYNAMIC_DECODE_DISABLED_NOTE",
    "MAX_EVENTS",
    "MAX_LISTED_ENDPOINTS",
    "MAX_SAMPLES_PER_TOPIC",
    "DecodeStatus",
    "DiscoveryCaches",
    "DiscoveryTracker",
    "LifecycleBuffer",
    "MetricsBuffer",
    "MetricsSample",
    "SampleCache",
    "VendorTag",
    "annotate_full",
    "annotate_partial",
    "annotate_raw",
    "announced_ns_of",
    "apply_builtin_samples",
    "build_endpoint_listing",
    "builtin_payload",
    "canonicalize_vendor_id",
    "cyclone_extract_guid",
    "cyclone_extract_hostname",
    "cyclone_extract_participant_name",
    "cyclone_extract_topic_name",
    "cyclone_extract_type_name",
    "cyclone_extract_vendor_id",
    "cyclone_qos_to_profile",
    "decode_dynamic_sample",
    "decode_field_value",
    "detect_mismatches",
    "detect_mismatches_across_endpoints",
    "duration_to_ns",
    "dynamic_type_name",
    "endpoint_record",
    "extract_publish_ns_from_payload",
    "extract_seq_from_payload",
    "fast_extract_guid",
    "fast_extract_hostname",
    "fast_extract_topic_name",
    "fast_extract_vendor_id",
    "fast_qos_to_profile",
    "format_guid",
    "format_participant_key",
    "is_alive_sample",
    "is_removal",
    "iter_field_names",
    "listing_from_samples",
    "participant_names",
    "summarize_by_topic",
    "take_bounded",
    "type_id_text",
    "user_topic_placeholder",
    "validate_domain_id",
    "vendor_id_from_guid",
]
